# Generated by Django 5.0.7 on 2025-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description provided', help_text='Course description'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Unknown location', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='a', help_text='Event title', max_length=80),
        ),
    ]
