# Generated by Django 5.0.7 on 2025-02-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('event', models.ForeignKey(help_text='Event associated with the description', on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Content text')),
                ('document', models.FileField(help_text='Content document', upload_to='documents/')),
                ('description', models.ForeignKey(help_text='Event associated with the content', on_delete=django.db.models.deletion.PROTECT, related_name='contents', to='event_description.description')),
            ],
        ),
    ]
