# Generated by Django 5.0.7 on 2025-02-07 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_description_event_duration_event_location_and_more'),
        ('user_event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='event',
            field=models.ForeignKey(help_text='Course associated with the user', on_delete=django.db.models.deletion.PROTECT, related_name='user_events', to='event.event'),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='user',
            field=models.ForeignKey(help_text='User associated with the course', on_delete=django.db.models.deletion.PROTECT, related_name='user_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
